#
# Create virtual environment with command:
#
#   $ CONDA_OVERRIDE_CUDA=11.7 conda env create --file conda-recipe.yaml
#

name: mcts-dpo
channels:
  - huggingface
  - pytorch
  - nvidia/label/cuda-11.7.1
  - defaults
  - conda-forge
dependencies:
  - python = 3.10
  - pip

  - pytorch::pytorch >= 1.13
  - pytorch::pytorch-mutex =*=*cuda*
  - transformers >= 4.29.0
  - datasets
  - tokenizers >= 0.13.3
  - sentencepiece
  - tensorboard
  - wandb
  - pip:
      - accelerate

  - nvidia/label/cuda-11.7.1::cuda-toolkit = 11.7

  - optree
  - scipy
  - nvitop
  - matplotlib-base
  - rich
  - tqdm
  - typing-extensions
  - ipdb
  - jsonlines
  - func_timeout
